---
apiVersion: v1
kind: Secret
metadata:
  name: pets-config
  labels:
    app.kubernetes.io/part-of: pets
type: Opaque
stringData:
  type: app-configuration
  pets_config.json: |-
    {
      "service": {
        "port": ":8080",
        "listen": "true"        
      },
      "backends": {},
      "observability": {
        "enable": false,
        "application": "micropets",
        "service": "pets",
        "cluster": "us-west",
        "shard": "primary",
        "server": "https://binz.wavefront.xxx",
        "token": "xxxx-xxx-yyyy-zzzz"        
      }
    }
