apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: pets-golang-aria-credentials
  annotations:
    autoscaling.knative.dev/minScale: "1"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/name: pets
    app.kubernetes.io/part-of: micropets
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
spec:
  name: app-config-aria
  service:
    apiVersion: v1
    kind: Secret
    name: aria-credentials
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: pets-golang
  env:
    - key: observability.enable
      name: MP_OBSERVABILITY.ENABLE
    - key: aria.ops.for.apps.token
      name: MP_OBSERVABILITY.TOKEN
    - key: aria.ops.for.apps.url
      name: MP_OBSERVABILITY.SERVER

