apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pets-golang
  namespace: micropets-int
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: micropets
    app.kubernetes.io/name: pets  
spec:
  source:
    git:
      url: https://github.com/bmoussaud/micropets-pets-golang/
      ref:
        branch: main
  serviceClaims:
    - name: app-config
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: pets-config
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-golang
    - name: gitops_commit_message
      value: pets int supplychain@cluster.local
